### PR TITLE
Add Typescript type definitions

### LINKED ISSUE #6: Need Typescript Support
Hello guys,

I need typescript support for the npm package.

### PR DESCRIPTION
**Pull request by jclusso**
Closes #6

### CODE REVIEW

**Comment by nolder3193** [comment]
I know you're not a fan of TypeScript but we should really avoid using `any` as it defeats the purpose of TypeScript. If this is just to be compliant for some third party then fair enough.

**Comment by jclusso** [comment]
> If this is just to be compliant for some third party then fair enough.

The library currently doesn't need updates if we add new options or new response data to our API and I'd like to keep it that way. This is just to appease Typescript users and I have no intention of us supporting it anymore than the bare minimum if it burdens the library with more updates.

**Review by nolder3193 — APPROVED** [review]

**Comment by ktwbc** [comment]
> > If this is just to be compliant for some third party then fair enough.
> 
> The library currently doesn't need updates if we add new options or new response data to our API and I'd like to keep it that way. This is just to appease Typescript users and I have no intention of us supporting it anymore than the bare minimum if it burdens the library with more updates.

But that completely defeats the point of typing, which is what TypeScript is. If you update the API with more info in the response, the type what type-hints at what is available and flags things at compile time.

**Comment by jclusso** [comment]
> If your source code was typed in the first place (i.e. it was natively .ts) then your contracts/typing are part of your source code, and it gets compiled down to .js with the typing file automatically by tsc (or esbuild or webpack or whatever bundler you're using). 

This is not a Typescript library and never will be. This was to appease those looking to use the library in Typescript projects.

**Pull request merged**
