### PR TITLE
Fix incorrect export in TS declaration

### LINKED ISSUE #15: Type definition file does not correspond to current code
Hey!

It looks like the type definition file (https://github.com/emailable/emailable-node/blob/master/lib/emailable.d.ts) was not updated with the code update, which leads to issues when using in TS environment.

### PR DESCRIPTION
**Pull request by jclusso**
Closes #15 and is a simplification of #16.

### CODE REVIEW

**Comment by jclusso** [comment]
@vgoloviznin  what do you think of this?

**Comment by vgoloviznin** [comment]
Getting all declarations in a single file is not correct from the TS POV as you actually miss what's being exported from other files than emailable.js. 

However, from getting the typings just for the emailable file this is correct and will work. 

I've also updated my PR with extra typings, the auto-type-generator missed them and I didn't spot this.

**Comment by jclusso** [comment]
> Getting all declarations in a single file is not correct from the TS POV as you actually miss what's being exported from other files than emailable.js.
> 
> However, from getting the typings just for the emailable file this is correct and will work.

So is this sufficient to make TS users happy? That's really the goal here and I'd like to avoid cluttering the project with extra files.

> I've also updated my PR with extra typings, the auto-type-generator missed them and I didn't spot this.

I noticed those regressions to a few of the fields.

Thanks for your help!

**Comment by vgoloviznin** [comment]
This should be sufficient, yes, as it fixes the main issue of the emailable export. You're welcome!

**Pull request merged**
